# Generated by Django 5.1 on 2024-08-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
