# Generated by Django 5.1 on 2024-08-20 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productattribute_product_alter_attribute_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.attribute'),
            preserve_default=False,
        ),
    ]
