# Generated by Django 5.1 on 2024-08-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attributevalue_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
    ]
